DROP TABLE IF EXISTS bronze_runes_mapping;
CREATE TABLE bronze_runes_mapping (
    stat_name VARCHAR(50),
    name VARCHAR(50)
);

INSERT INTO bronze_runes_mapping (stat_name, name) VALUES
('% Critique', 'Rune Cri'),
('Intelligence', 'Rune Ine'),
('Agilité', 'Rune Age'),
('Dommages Air', 'Rune Do Air'),
('Tacle', 'Rune Ta'),
('Force', 'Rune Fo'),
('Fuite', 'Rune Fu'),
('Chance', 'Rune Cha'),
('PM', 'Rune PM'),
('Prospection', 'Rune Prospe'),
('Soins', 'Rune Soi'),
('Dommages Terre', 'Rune Do Ter'),
('Sagesse', 'Rune Sa'),
('Dommages Neutre', 'Rune Do Neu'),
('PA', 'Rune PA'),
('Portée', 'Rune Po'),
('Dommages Eau', 'Rune Do Eau'),
('Dommages Feu', 'Rune Do Feu'),
('Dommages', 'Rune Do'),
('Invocations', 'Rune Invo'),
('Dommages critiques', 'Rune Do Cri'),
('Résistance Critiques', 'Rune Ré Cri'),
('Puissance', 'Rune Pui'),
('Dommages Poussée', 'Rune Do Pou'),
('% Résistance Terre', 'Rune Ré Terre'),
('Retrait PA', 'Rune Re PA'),
('Retrait PM', 'Rune Re PM'),
('% Résistance Feu', 'Rune Ré Feu'),
('% Résistance Eau', 'Rune Ré Eau'),
('% Résistance Air', 'Rune Ré Air'),
('Résistance Feu', 'Rune Ra Feu'),
('Résistance Eau', 'Rune Ra Eau'),
('Résistance Air', 'Rune Ra Air'),
('Résistance Terre', 'Rune Ra Ter'),
('Résistance Neutre', 'Rune Ra Neu'),
('Esquive PM', 'Rune Es PM'),
('% Résistance Neutre', 'Rune Ré Neu'),
('Résistance Poussée', 'Rune Ré Pou'),
('Esquive PA', 'Rune Es PA'),
('Renvoie  dommages', 'Rune Re Do'),
('Puissance (pièges)', 'Rune Pui Pi'),
('Dommages Pièges', 'Rune Do Pi'),
('% Résistance mêlée', 'Rune Ré Mê'),
('% Dommages mêlée', 'Rune Do Mê'),
("% Dommages d\'armes", 'Rune Do Ar'),
('% Dommages aux sorts', 'Rune Do So'),
('% Dommages distance', 'Rune Do Dis'),
('% Résistance distance', 'Rune Ré Dis');
